### ISSUE TITLE
Molecule delegated driver is being ignored; unable to determine where to place Zuul variables

### ISSUE THREAD

**Issue by jacklh9** [ansible-community/pytest-molecule#36]
Greetings,

I have a working molecule test using "molecule verify" to run some tests with testinfra verifier. I'm trying to get pytest to run my ansible tests (so I can also make use of its reporting features, debugging, etc) using your pytest-molecule. I am using "delegated" driver (but currently have empty create/destroy yml files but want for future use). Running "pytest -m delegated" results in the following error:

```
Molecule delegated driver was not enabled because missing zuul.build variable in current inventory. We will tag scenarios using it with 'skip' marker.
```

Sure enough, my molecule tests are skipped:

```
molecule/default/molecule.yml s                                                                                                            [100%]
```

I see in your documentation that you state:

>Due to the potential destructive nature of delegated driver, scenarios running it will run only if Ansible detects one of the following variables as defined: zuul, use_for_testing.

I'm trying to figure out where in my molecule.yml I need to include var "zuul: True" or "use_for_testing: True" or "zuul.build: /tmp/zuul" since I am not using an actual inventory file and am relying on molecule's provision section to build me a dynamic inventory file.

I have tried different permutations, but all have the same error that my molecule tests are being skipped because zuul.build is missing.

```
provisioner:
  name: ansible
  connection_options:
    host_key_checking: False
    ansible_ssh_user: ${vm_user}
    ansible_password: ${vm_pass}

  inventory:
    group_vars:
      all:
        zuul: True
        use_for_testing: True
        zuul.build: /tmp/zuul
```

Can you provide specific insight as to where exactly the "zuul" and/or "zuul.build" variable needs to be defined (and also what value)?

Current core pip requirements:
```
ansible==2.7.11
molecule==2.20.1
mock
pyqt5<=5.12
spyder
typed-ast
jinja2==2.10
pyyaml==3.13
pytest-bdd
pytest
testinfra==1.19.0
pytest-molecule==1.1.0
```

Full molecule.yml:
```
---
dependency:
  name: galaxy
driver:
  name: delegated
lint:
  name: yamllint
platforms:
  - name: ${vm_ip}
provisioner:
  name: ansible
  connection_options:
    #TO DO: host key checking does not appear to be working
    host_key_checking: False
    ansible_ssh_user: ${vm_user}
    ansible_password: ${vm_pass}

  inventory:
    group_vars:
      all:
        # pytest-molecule:  Due to the potential destructive nature of delegated driver, 
        # scenarios running it will run only if Ansible detects one of the following 
        # variables as defined: zuul, use_for_testing.
        # SOURCE: https://pypi.org/project/pytest-molecule/
        zuul: True
        use_for_testing: True
        zuul.build: /tmp/zuul
        
  # ansible.cfg
  #config_options:
  #  defaults:
  # ...

  log: True
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  directory: ../../steps
  lint:
    name: flake8
  options:
    v: 1
```

Thank you.

**Comment by jacklh9** [comment]
Version info reported by "molecule verify":
```
============================= test session starts ==============================
    platform linux -- Python 3.6.8, pytest-5.1.2, py-1.8.0, pluggy-0.12.0 -- /home/jack/virtualenv/venv_rhel_functional_tests/bin/python3
    rootdir: /home/jack/git/Azure/Tower/Ansible-Role-VMware-Create-VM/Create-VM/tests/functional, inifile: pytest.ini
    plugins: bdd-3.2.1, molecule-1.1.0, testinfra-1.19.0
```
This is running on Ubuntu 18.04 via WSL on Windows 10 work laptop with latest updates from dist-upgrade. 

```
Linux DW202N2 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

wheel and setuptools upgraded on system. Using virtual env with "pip install pip wheel setuptools --upgrade" also performed, although there was an error during bdist_wheel build when building the venv environment, so possible that something didn't compile for pytest-molecule. I'm using delegated mode because I'm not dealing with docker containers. Not sure why zuul is needed for my setup.

**Comment by jacklh9** [comment]
Oddly, if I run the following:

```
ansible localhost -e ansible_connection=local -o -m shell -a "echo {% if zuul is defined %}True{% else %}False{% endif %}" --extra-vars "zuul=1"
```

I can get the above to return True:

```
localhost | CHANGED | rc=0 | (stdout) True
```
But if I place the following in my provision section, it's ignored and reports the same error:

```
provisioner:
  name: ansible
  ansible_args:
    - --extra-vars "zuul=1"
```
